config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :following, :followers
    end

    resource :relationships, only: [:create, :destroy]

  end

  resources :movies do
    resources :movie_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  get "search" => "searches#search"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
  attachment :movie_image, destroy: false

  belongs_to :user
  has_many :movie_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
    # 引数に渡したユーザーを既にイイねしてるかを判定する
  end

  def self.looks(search,word)
    # whereメソッドを使いデータベースから該当データを取得し、変数に代入
    if search == "perfect_match"
      @movie = Movie.where("title LIKE?", "#{word}")
    elsif search == "forward_match"
      @movie = Movie.where("title LIKE?", "#{word}%")
    elsif search == "backward_match"
      @movie = Movie.where("title LIKE?", "%#{word}")
    elsif search == "partical_match"
      @movie = Movie.where("title LIKE?", "%#{word}%")
    else
      @movie = Movie.all
    end
  end


end

app/models/movie_comment.rb
class MovieComment < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  validates :comment, presence: true

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :movies, dependent: :destroy
  has_many :movie_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  attachment :profile_image, destroy: false

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true


  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 自分がフォローする側の関係性
  has_many :followings, through: :relationships, source: :followed
  # 与フォロー関係を通じて参照→自分がフォローしている人

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローされる側の関係性
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→自分をフォローしている人


  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
    # 引数に渡したユーザを、フォローしているかどうかを判定する
  end

  def self.looks(search,word)
    # whereメソッドを使いデータベースから該当データを取得し、変数に代入
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partical_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!,except: [:top]
  # アクセス権限
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @movie = Movie.find(params[:movie_id])
    favorite = current_user.favorites.new(movie_id: @movie.id)
    favorite.save
    # redirect_to movie_path(movie)
    # リダイレクト先は非同期通信を実装のためコメントアウト
  end

  def destroy
    @movie = Movie.find(params[:movie_id])
    favorite = current_user.favorites.find_by(movie_id: @movie.id)
    favorite.destroy
    # redirect_to movie_path(movie)
    # リダイレクト先は非同期通信を実装のためコメントアウト
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/movie_comments_controller.rb
class MovieCommentsController < ApplicationController

  def create
    @movie = Movie.find(params[:movie_id])
    @user = current_user
    movie_comment = MovieComment.new(movie_comment_params)
    movie_comment.user_id = current_user.id
    movie_comment.movie_id = @movie.id
    if movie_comment.save
      # redirect_to movie_path(movie.id)
      # リダイレクト先は非同期通信を実装のためコメントアウト
    else
      render "movies/show"
    end
  end

  def destroy
    @movie = Movie.find(params[:movie_id])
    @user = current_user
    MovieComment.find(params[:id]).destroy
    # redirect_to movie_path(movie.id)
    # リダイレクト先は非同期通信を実装のためコメントアウト
  end

  private

  def movie_comment_params
    params.require(:movie_comment).permit(:comment)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.user = current_user

    if @movie.save
      redirect_to movies_path, notice: "新規投稿に成功しました"
    else
      render "new"
    end
  end

  def index
    @movies = Movie.page(params[:page]).reverse_order
    @quantity = Movie.count

  end

  def show
    @movie = Movie.find(params[:id])
    @user = current_user
    @movie_user = @movie.user
    @movie_comment = MovieComment.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to movie_path(@movie)
    else
      render "edit"
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to user_path(@movie.user)
  end

  private
  def movie_params
    params.require(:movie).permit(:title, :body, :movie_image, :evaluation)
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
    # 遷移元のURLを取得してリダイレクト
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
    # 遷移元のURLを取得してリダイレクト
  end



end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @range = params[:range]
    @word = params[:word]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
      # 検索方法と検索ワードを参照してデータを検索
      # looksメソッドを使用し、検索内容を取得し、変数を代入
       @quantity = @users.count
    else
      @movies = Movie.looks(params[:search], params[:word]).page(params[:page]).reverse_order
      # 検索方法と検索ワードを参照してデータを検索
      # looksメソッドを使用し、検索内容を取得し、変数を代入
       @quantity = @movies.count
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.page(params[:page]).reverse_order
  end

  def show
    @user = User.find(params[:id])
    @movies = @user.movies
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render "edit"
    end
  end

  def following
    @user = User.find_by(id: params[:id])
    @users = @user.followings
  end

  def followers
    @user  = User.find_by(id: params[:id])
    @users = @user.followers
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/movie_comments_helper.rb
module MovieCommentsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorite-btn.html.erb
<% if movie.favorited_by?(current_user) %>
  <p>
    <%= link_to movie_favorites_path(movie), method: :delete, remote: true do %>
      ♥<%= movie.favorites.count %>イイね
    <% end %>
  </p>
<% else %>
  <p>
    <%= link_to movie_favorites_path(movie), method: :post, remote: true do %>
      ♡<%= movie.favorites.count %>イイね
    <% end %>
  </p>
<% end %>

app/views/favorites/create.js.erb
$("#favorite-btn_<%= @movie.id %>").html("<%= j(render 'favorites/favorite-btn', movie: @movie) %>");

app/views/favorites/destroy.js.erb
$("#favorite-btn_<%= @movie.id %>").html("<%= j(render 'favorites/favorite-btn', movie: @movie) %>");

app/views/homes/top.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
        <h1 class="top-title">Film Diary</h1>
        <section class="top-introduction">
          <h3>楽しむ、繋がる、記録する。</h3>
          <!--<p>映画好きが映画好きと繋がり、作品1つ1つの解釈の幅が広がるサイトです。</p>-->
          <p>人と繋がり映画lifeをより良いものに、、、</p>
        </section>
        <div id="slider">
          <!--画像スライダーのイメージ画像-->
            <%= image_tag 'jake-hills-23LET4Hxj_U-unsplash.jpg' %>
            <div class="position-relative">
              <%= image_tag 'chris-murray-YvPxyGzaFJ4-unsplash.jpg', class: 'chris-murray-image' %>
            </div>
            <%= image_tag 'noom-peerapong-2uwFEAGUm6E-unsplash.jpg' %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/movie_comments/_comment-index.html.erb
<div class="">
  <%= movie.movie_comments.count %>件のコメント
</div>
<% movie.movie_comments.each do |comment| %>
  <% unless comment.id.nil? %>
    <div class="row" id="communityCommentsId-<%= movie.id %>">
      <div class="col-md-12">
        <div class="card" style="width: 1200px;">
          <div class="comment-widgets m-b-20">
            <div class="d-flex flex-row comment-row">
              <div class="">
                <span class="round comment-avatar p-3 img_profile">
                  <%=link_to user_path(id: comment.user.id), method: :get do %>
                    <%= attachment_image_tag(comment.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", class: "attachment user profile_image mt-2" )%>
                  <% end %>
                </span>
              </div>
              <div class="comment-text w-100">
                <div class="community-comment-text pt-2 pl-2 pr-2">
                  <div class="comment-header">
                    <span style="font-size: 16px; font-weight: 600; "><%= comment.user.name %>さん</span>
                    <% if comment.user == current_user %>
                      <span class="action-icons" style="width: 88%;text-align: right;">
                        <%#= link_to community_comments_edit_path(community_post.uid, comment.id), method: :get, data: { remote: true } do %>
                          <!--<svg style="vertical-align: -1px; fill: gainsboro;" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" enable-background="" height="16px" id="Layer_1" version="1.1" viewBox="0 0 45 45" width="16px" xml:space="preserve"><g><rect  height="23" transform="matrix(-0.7071 -0.7072 0.7072 -0.7071 38.2666 48.6029)" width="11" x="23.7" y="4.875"/><path d="M44.087,3.686l-2.494-2.494c-1.377-1.377-3.61-1.377-4.987,0L34.856,2.94l7.778,7.778l1.749-1.749   C45.761,7.593,45.465,5.063,44.087,3.686z" /><polygon  points="16,22.229 16,30 23.246,30  "/><path d="M29,40H5V16h12.555l5-5H3.5C1.843,11,0,11.843,0,13.5v28C0,43.156,1.843,45,3.5,45h28   c1.656,0,2.5-1.844,2.5-3.5V23.596l-5,5V40z"/></g></svg>-->
                        <%# end %>
                        <%= link_to movie_movie_comment_path(movie, comment), method: :delete, data: { confirm: "本当に削除しますか？", remote: true } do %>
                          <svg style="vertical-align: -1px; fill: gainsboro;" xmlns="http://www.w3.org/2000/svg" id="Layer_1" enable-background="new 0 0 512 512" height="16px" viewBox="0 0 512 512" width="16px"><g><path d="m424 64h-88v-16c0-26.51-21.49-48-48-48h-64c-26.51 0-48 21.49-48 48v16h-88c-22.091 0-40 17.909-40 40v32c0 8.837 7.163 16 16 16h384c8.837 0 16-7.163 16-16v-32c0-22.091-17.909-40-40-40zm-216-16c0-8.82 7.18-16 16-16h64c8.82 0 16 7.18 16 16v16h-96z"/><path d="m78.364 184c-2.855 0-5.13 2.386-4.994 5.238l13.2 277.042c1.22 25.64 22.28 45.72 47.94 45.72h242.98c25.66 0 46.72-20.08 47.94-45.72l13.2-277.042c.136-2.852-2.139-5.238-4.994-5.238zm241.636 40c0-8.84 7.16-16 16-16s16 7.16 16 16v208c0 8.84-7.16 16-16 16s-16-7.16-16-16zm-80 0c0-8.84 7.16-16 16-16s16 7.16 16 16v208c0 8.84-7.16 16-16 16s-16-7.16-16-16zm-80 0c0-8.84 7.16-16 16-16s16 7.16 16 16v208c0 8.84-7.16 16-16 16s-16-7.16-16-16z"/></g></svg>
                        <% end %>
                      </span>
                    <% end %>
                  </div>
                  <div class=""><%= simple_format(comment.comment) %></div>
                </div>
                <div class="date pb-1" style="color: rgb(176, 179, 184);">
                  <%= time_ago_in_words(comment.created_at) %> ago
                </div>
              </div>
            </div>
          </div><!-- comment-widgets m-b-20 -->
        </div><!-- card -->
      </div><!-- col-md-12 -->
    </div><!-- row -->
  <% end %>
<% end %>

app/views/movie_comments/create.js.erb
$(".comment-history").html("<%= j(render 'movie_comments/comment-index', movie: @movie, user: @user) %>");
$("#movie_comment_comment").val('');
<!--コメントを投稿した際コメント欄を空にする記述-->

app/views/movie_comments/destroy.js.erb
$(".comment-history").html("<%= j(render 'movie_comments/comment-index', movie: @movie, user: @user) %>");

app/views/movies/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>映画情報編集画面</h2>
        <%= render 'layouts/errors', obj: @movie %>
        <%= form_with model:@movie, local:true do |f| %>

          <div class="form_group">
            <%= f.label :Image %>
            <%= f.attachment_field :movie_image, class: "form-control-file movie_image" %>
          </div>

          <div class="form_group">
            <%= f.label :Title %>
            <%= f.text_field :title, class: "form-control movie_title" %>
          </div>

          <div class="form_group">
            <%= f.label :Impressions %>
            <%= f.text_area :body, class: "form-control movie_body" %>
          </div>

          <div id="evaluate_stars">
            <%= f.label :Evaluation %>
            評価機能
          </div>

          <div class="form_group">
            <%= f.submit class: "btn btn-secondary" %>
          </div>
        <% end %>
        <script>
            // 実行する処理を記述
          $('#evaluate_stars').raty({
            starOn: "<%= asset_path('star-on.png') %>",
            starOff: "<%= asset_path('star-off.png') %>",
            starHalf: "<%= asset_path('star-half.png') %>",
            scoreName: 'movie[evaluation]' //登録するモデル名とカラム名を記述
          });
        </script>
      </div>
    </div>
  </div>
</main>

app/views/movies/index.html.erb
<main>
  <div class="container">
    <h2>映画投稿一覧<span>(<%= @quantity %>件)</span></h2>
    <div class="row">
      <div class="movie_container">
        <% @movies.each do |movie| %>
          <div class="movie_item">
            <%= link_to movie_path(movie.id) do %>
              <%= attachment_image_tag(movie, :movie_image, :fill, 200, 200, follback: "no_image.jpg") %>
            <% end %>
            <p>タイトル：<%= movie.title %></p>
            <p>投稿者：<%= movie.user.name %></p>
            <p>コメント数：<%= movie.movie_comments.count %></p>
            <p><%= movie.favorites.count %>イイね</p>
          </div>
        <% end %>
      </div>
    </div>
      <%= paginate @movies %>
  </div>
</main>

app/views/movies/new.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>映画新規投稿</h2>
        <%= render 'layouts/errors', obj: @movie %>
        <%= form_with model:@movie, local:true do |f| %>

          <div class="form_group">
            <%= f.label :Image %>
            <%= f.attachment_field :movie_image, class: "form-control-file movie_image" %>
          </div>

          <div class="form_group">
            <%= f.label :Title %>
            <%= f.text_field :title, class: "form-control movie_title" %>
          </div>

          <div class="form_group">
            <%= f.label :Impressions %>
            <%= f.text_area :body, class: "form-control movie_body" %>
          </div>

          <div id="evaluate_stars">
            <%= f.label :Evaluation %>
          </div>

          <div class="form_group">
            <%= f.submit class: "btn btn-secondary" %>
          </div>
        <% end %>
        <script>
        $(function(){
  // 実行する処理を記述
          $('#evaluate_stars').raty({
            starOn: "<%= asset_path('star-on.png') %>",
            starOff: "<%= asset_path('star-off.png') %>",
            starHalf: "<%= asset_path('star-half.png') %>",
            scoreName: 'movie[evaluation]' //登録するモデル名とカラム名を記述
          });
        });

        </script>
      </div>
    </div>
  </div>
</main>

app/views/movies/show.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="image_field col-md-7">
        <%= attachment_image_tag(@movie, :movie_image, :fill, 250, 170, fallback: "no_image.jpg") %>
        <div id="favorite-btn_<%= @movie.id %>">
          <%= render 'favorites/favorite-btn', movie: @movie %>
          <!--イイねボタンの表示-->
        </div>
      </div>

      <div class="introduction_field col-md-4">
        <h2><%= @movie.title %></h2>
        <p><%= @movie.body %></p>
        <% if @movie_user.id == current_user.id %>
          <p><%= link_to "Edit", edit_movie_path(@movie), class:"btn btn-outline-warning" %>
            　<%= link_to "Destroy", movie_path(@movie), method: :delete, data: {confirm: '本当に消去しますか？'}, class: "btn btn-outline-danger" %>
          </p>
        <% end %>
         <div class="movie-evaluation" data-score="<%= @movie.evaluation %>"></div>
         <!--評価の表示-->
      </div>
    </div>
    <script>
      $('.movie-evaluation').raty({
        readOnly: true,
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        starHalf: "<%= asset_path('star-half.png') %>",
        score: function() {
          return $(this).attr('data-score');
        },
      });
    </script>
    <div class="row">
      <div class="col-md-7">
        <div class="comment-history">
          <%= render 'movie_comments/comment-index', movie: @movie, user: @user %>
          <!--コメント一覧表示-->
        </div>
      </div>
      <div class="col-md-4">
        <div class="new-comment">
          <%= form_with(model:[@movie, @movie_comment]) do |f| %>
            <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %><br>
            <%= f.submit "コメントを投稿" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/searches/search.html.erb
<% if @range == "User" %>
  <main>
    <div class="container">
      <h2><%= @word %><span>(<%= @quantity %>件)</span></h2>
      <div class="row">
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
              <th>post count</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %>
                </td>
                <td><%= user.name %></td>
                <td></td>
                <td><%= user.movies.count %></td>
                <td><%= link_to "show", user_path(user), class: "btn btn-outline-primary" %></td>
                <td></td>
                <td>
                  <% if current_user.following?(user) %>
                    <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class: "btn btn-primary" %>
                  <% else %>
                    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </main>
<% else %>
  <main>
    <div class="container">
      <h2><%= @word %><span>(<%= @quantity %>件)</span></h2>
      <div class="row">
        <div class="movie_container">
          <% @movies.each do |movie| %>
            <div class="movie_item">
              <%= link_to movie_path(movie.id) do %>
                <%= attachment_image_tag(movie, :movie_image, :fill, 200, 200, follback: "no_image.jpg") %>
              <% end %>
              <p>タイトル：<%= movie.title %></p>
              <p>投稿者：<%= movie.user.name %></p>
              <p>コメント：<%= movie.movie_comments.count %></p>
              <p><%= movie.favorites.count %></p>
            </div>
          <% end %>
        </div>
      </div>
      <%= paginate @movies %>
    </div>
  </main>
<% end %>

app/views/users/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>会員情報編集画面</h2>
        <%= render 'layouts/errors', obj: @user %>
        <%= form_with model:@user, local:true do |f| %>

          <div class="form_group">
            <%= f.label :Image %>
            <%= f.attachment_field :profile_image, class: "form-control-file profile_image" %>
          </div>

          <div class="form_group">
            <%= f.label :Name %>
            <%= f.text_field :name, class: "form-control user_name" %>
          </div>

          <div class="form_group">
            <%= f.submit class: "btn btn-secondary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/followers.html.erb
<main>
  <div class="container">
    <div class="row">
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th>Post Count</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %></td>
              <td>
                <%= link_to user_path(user.id) do %>
                  <%= user.name %>
                <% end %>
              </td>
              <td></td>
              <td><%= user.movies.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</main>

app/views/users/following.html.erb
<main>
  <div class="container">
    <div class="row">
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th>Post Count</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %></td>
              <td>
                <%= link_to user_path(user.id) do %>
                  <%= user.name %>
                <% end %>
              </td>
              <td></td>
              <td><%= user.movies.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <div class="container">
    <div class="row">
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th>post count</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %>
              </td>
              <td><%= user.name %></td>
              <td></td>
              <td><%= user.movies.count %></td>
              <td><%= link_to "show", user_path(user.id), class: "btn btn-outline-primary" %></td>
              <td></td>
              <td>
                <% if current_user.following?(user) %>
                  <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class: "btn btn-primary" %>
                <% else %>
                  <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
                <% end %>
              </td>
            </tr>
            <% end %>
        </tbody>
      </table>
    </div>
    <%= paginate @users %>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="image-field col-md-7">
        <%= attachment_image_tag(@user, :profile_image, :fill, 200, 200, fallback: "no_image.jpg") %>
        <div class="follow">
          <p>フォロー：
            <%= link_to following_user_path(@user) do %>
              <%= @user.followings.count %>
            <% end %>
          </p>
          <p>フォロワー：
          <%= link_to followers_user_path(@user) do %>
            <%= @user.followers.count %>
          <% end %>
          </p>
          <% if current_user.following?(@user) %>
            <%= link_to "フォローを外す", user_relationships_path(@user.id), method: :delete, class: "btn btn-primary" %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "btn btn-success" %>
          <% end %>
        </div>
      </div>

      <div class="introduction-field col-md-4">
        <h2><%= @user.name %></h2>
        <% if @user.id ==current_user.id %>
          <p><%= link_to "Edit", edit_user_path(@user), class:"btn btn-outline-warning" %>
              <%= link_to "New", new_movie_path, class:"btn btn-outline-info" %>
          </p>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <% @movies.each do |movie| %>
          <div class="movie-item">
            <%= link_to movie_path(movie.id) do %>
              <%= attachment_image_tag(movie, :movie_image, :fill, 200, 200, fallback: "no_image.jpg") %>
            <% end %>
            <p>タイトル：<%= movie.title %></p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>