config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :following, :followers
    end

    resource :relationships, only: [:create, :destroy]

  end

  resources :movies do
    resources :movie_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  get "search" => "searches#search"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
  attachment :movie_image, destroy: false

  belongs_to :user
  has_many :movie_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
    # 引数に渡したユーザーを既にイイねしてるかを判定する
  end

  def self.looks(search,word)
    # whereメソッドを使いデータベースから該当データを取得し、変数に代入
    if search == "perfect_match"
      @movie = Movie.where("title LIKE?", "#{word}")
    elsif search == "forward_match"
      @movie = Movie.where("title LIKE?", "#{word}%")
    elsif search == "backward_match"
      @movie = Movie.where("title LIKE?", "%#{word}")
    elsif search == "partical_match"
      @movie = Movie.where("title LIKE?", "%#{word}%")
    else
      @movie = Movie.all
    end
  end


end

app/models/movie_comment.rb
class MovieComment < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  validates :comment, presence: true

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :movies, dependent: :destroy
  has_many :movie_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  attachment :profile_image, destroy: false

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true


  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 自分がフォローする側の関係性
  has_many :followings, through: :relationships, source: :followed
  # 与フォロー関係を通じて参照→自分がフォローしている人

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローされる側の関係性
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→自分をフォローしている人


  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
    # 引数に渡したユーザを、フォローしているかどうかを判定する
  end

  def self.looks(search,word)
    # whereメソッドを使いデータベースから該当データを取得し、変数に代入
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partical_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!,except: [:top]
  # アクセス権限
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @movie = Movie.find(params[:movie_id])
    favorite = current_user.favorites.new(movie_id: @movie.id)
    favorite.save
    # redirect_to movie_path(movie)
    # リダイレクト先は非同期通信を実装のためコメントアウト
  end

  def destroy
    @movie = Movie.find(params[:movie_id])
    favorite = current_user.favorites.find_by(movie_id: @movie.id)
    favorite.destroy
    # redirect_to movie_path(movie)
    # リダイレクト先は非同期通信を実装のためコメントアウト
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.user = current_user

    if @movie.save
      redirect_to movies_path, notice: "新規投稿に成功しました"
    else
      render "new"
    end
  end

  def index
    @movies = Movie.page(params[:page]).reverse_order
    @quantity = Movie.count

  end

  def show
    @movie = Movie.find(params[:id])
    @user = current_user
    @movie_user = @movie.user
    @movie_comment = MovieComment.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to movie_path(@movie)
    else
      render "edit"
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to user_path(@movie.user)
  end

  private
  def movie_params
    params.require(:movie).permit(:title, :body, :movie_image, :evaluation)
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @range = params[:range]
    @word = params[:word]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
      # 検索方法と検索ワードを参照してデータを検索
      # looksメソッドを使用し、検索内容を取得し、変数を代入
       @quantity = @users.count
    else
      @movies = Movie.looks(params[:search], params[:word]).page(params[:page]).reverse_order
      # 検索方法と検索ワードを参照してデータを検索
      # looksメソッドを使用し、検索内容を取得し、変数を代入
       @quantity = @movies.count
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.page(params[:page]).reverse_order
  end

  def show
    @user = User.find(params[:id])
    @movies = @user.movies
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render "edit"
    end
  end

  def following
    @user = User.find_by(id: params[:id])
    @users = @user.followings
  end

  def followers
    @user  = User.find_by(id: params[:id])
    @users = @user.followers
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/movie_comments_helper.rb
module MovieCommentsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this Contents from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class='container mt-5'>
      <div class='row'>
        <div class='mx-auto'>
        </div>
      </div>
    </div>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Film Diary</span></a>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li><%= link_to "Home", root_path, class: 'fas fa-home nav-link text-light' %></li>
            <li><%= link_to "Users", users_path, class: 'fas fa-users nav-link text-light' %></li>
            <li><%= link_to "Movies", movies_path, class: 'fas fa-film nav-link text-light' %></li>
            <li><%= link_to "My page", user_path(current_user), class: 'fas fa-user nav-link text-light'%></li>
            <li><%= link_to "logout", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %></li>
          <% else %>
            <li><%= link_to "Home", root_path, class: 'fas fa-home nav-link text-light' %></li>
            <li><%= link_to "Sign_up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %></li>
            <li><%= link_to "login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<% if user_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
    <!--検索内容を、先ほど作成したルーティングに送信する-->
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Movie']]) %>
      <!--userモデルとmovieモデルを検索出来る様にする-->
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backword_match"], ["部分一致","partial_match"]]) %>
      <!--検索方法を定義-->
      <%= f.submit "検索", class: "btn btn-secondary" %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FilmDiary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/search' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>